# 汉化版+阿里p3c验证
version: "2"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar 
      - sonar.jdbc.password=sonar 
      - sonar.security.realm=LDAP
      - ldap.url=ldap://10.0.5.99:3268
      - ldap.bindDn=ldapadmin
      - ldap.bindPassword=LDAP@admin
      - ldap.user.baseDn=OU=Szewec,DC=szewec,DC=com
      - ldap.user.request=(&(objectClass=organizationalPerson)(sAMAccountName={login}))
      - ldap.user.realNameAttribute=cn
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./plugin/rhinoceros/sonar-pmd-plugin-3.2.0-SNAPSHOT.jar:/opt/sonarqube/extensions/plugins/sonar-pmd-plugin-3.2.0-SNAPSHOT.jar
      - ./plugin/sonar-l10n-zh-plugin-8.6.jar:/opt/sonarqube/extensions/plugins/sonar-l10n-zh-plugin-8.6.jar

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgres/postgresql:/var/lib/postgresql
      - ./postgres/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
